services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  clone:
    build: ./clone
    ports:
      - "8001:8001"
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - clone
